handle: newsType
name: 'News type'
siteSettings:
  7c8dfb29-57c2-49ad-81d4-5b35c7459794:
    hasUrls: true
    template: ''
    uriFormat: 'news-type/{slug}'
  f43d34ee-b020-4342-a0cb-230c2932c0b3:
    hasUrls: true
    template: ''
    uriFormat: 'news-type/{slug}'
structure:
  maxLevels: null
  uid: 65e64cfc-be47-4b1e-8692-ef189d708a19
