fieldLayouts:
  4505687c-8988-48e7-8d5d-bbc719461f86:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsType
name: 'News type'
siteSettings:
  7c8dfb29-57c2-49ad-81d4-5b35c7459794:
    hasUrls: true
    template: news/category-listing.html
    uriFormat: 'news-type/{slug}'
  f43d34ee-b020-4342-a0cb-230c2932c0b3:
    hasUrls: true
    template: news/category-listing.html
    uriFormat: 'news-type/{slug}'
structure:
  maxLevels: null
  uid: 65e64cfc-be47-4b1e-8692-ef189d708a19
