fieldLayouts:
  6bb5bd9e-41da-4e5f-8c0c-efd73620a411:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsImages
hasUrls: true
name: 'News images'
settings:
  path: $ASSETS_FOLDER/news
sortOrder: 2
type: craft\volumes\Local
url: $ASSETS_BASE_URL
