dateModified: 1599635155
email:
  fromEmail: marie@studio24.net
  fromName: 'Craft CMS test'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
    settings:
      allowIps: ''
      checkInvalidLogins: ''
      denyIps: ''
      enabled: '1'
      forcedRedirect: null
      invalidLoginWindowDuration: '3600'
      loginPath: ''
      maxInvalidLogins: '10'
      password: w3ccraft24
      protectedUrls: ''
      siteSettings:
        __assoc__:
          -
            - default
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
          -
            - craftCmsEnFrancais
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
      template: ''
      unprotectedUrls: ''
      useRemoteIp: ''
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  smartdown:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft CMS test'
  schemaVersion: 3.5.13
  timeZone: Europe/London
