dateModified: 1599227889
email:
  fromEmail: marie@studio24.net
  fromName: 'Craft CMS test'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  smartdown:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft CMS test'
  schemaVersion: 3.5.13
  timeZone: Europe/London
