enableVersioning: true
handle: mainNavigation
name: 'Main navigation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - ''
      -
        - refresh
        - '1'
propagationMethod: siteGroup
siteSettings:
  7c8dfb29-57c2-49ad-81d4-5b35c7459794:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  f43d34ee-b020-4342-a0cb-230c2932c0b3:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: d31bc7dc-2a80-48c7-bae5-90b445cada2e
type: structure
